[build]
  base = "frontend"
  publish = "dist/client"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://cvpilot-emhy.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
