import { GraphState } from '../../types';
import { resumeJsonPrompt } from '../../prompts';
import { getLLMClient } from '../../llm/client';
import { parseJSON, retryWithBackoff } from '../../utils';

export async function generateResumeJsonNode(state: GraphState): Promise<Partial<GraphState>> {
  if (!state.resumeContext) {
    throw new Error('Missing resumeContext in state');
  }

  const client = getLLMClient();

  const resumeData = {
    summary: state.generatedSummary,
    experiences: state.selectedExperiences,
    projects: state.selectedProjects,
    skills: state.selectedSkills,
    education: state.resumeContext.educations.map((e) => ({
      school: e.school,
      degree: e.degree,
      field: e.field || undefined,
      gpa: e.gpa || undefined,
      startDate: e.startDate?.toISOString().split('T')[0],
      endDate: e.endDate?.toISOString().split('T')[0],
    })),
    certificates: state.resumeContext.certificates.map((c) => ({
      name: c.name,
      issuer: c.issuer,
    })),
    achievements: state.resumeContext.achievements.map((a) => a.title),
  };

  const response = await retryWithBackoff(async () => {
    return client.call([
      { role: 'system', content: resumeJsonPrompt },
      {
        role: 'user',
        content: `Compile this resume data into final JSON:\n\n${JSON.stringify(resumeData, null, 2)}`,
      },
    ], { json: true });
  });

  const generatedResume = parseJSON(response.content) as any;

  // Validate structure
  if (!generatedResume.summary || !Array.isArray(generatedResume.experiences)) {
    throw new Error('Invalid JSON structure generated by LLM');
  }

  // Merge metadata from state
  const finalResumeJson = {
    ...generatedResume,
    metadata: {
      targetRole: state.metadata.targetRole,
      companyName: state.metadata.companyName,
      generationSessionId: state.metadata.generationSessionId,
      generatedAt: new Date().toISOString(),
      keywordMatches: state.metadata.keywordMatches,
      selectionRationale: state.metadata.selectionRationale,
    },
  };

  return {
    generatedResumeJson: finalResumeJson as any,
  };
}
